// <auto-generated />
using System;
using Infrastructure.Database.Game;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Game.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260816231912_SlavicRework")]
    partial class SlavicRework
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Game.ArenaItems.ArenaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ArenaItems", "game");
                });

            modelBuilder.Entity("Domain.Game.Arenas.Arena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundAsset")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<int[]>("GameModes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("GridHeight")
                        .HasColumnType("integer");

                    b.Property<int>("GridWidth")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Arenas", "game");
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaEnemies.ArenaEnemy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("EnemyId");

                    b.ToTable("ArenaEnemies", "game");
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaPlacedItems.ArenaPlacedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ArenaId", "ItemId");

                    b.ToTable("ArenaPlacedItems", "game");
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaTerrainCells.ArenaTerrainCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Terrain")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.ToTable("ArenaTerrainCells", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterClasses.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CharacterClasses", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSpecId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSpecId", "Type")
                        .IsUnique();

                    b.ToTable("CharacterSpecAbilities", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbilityActionAsset", b =>
                {
                    b.Property<Guid>("CharacterSpecAbilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<int>("Variant")
                        .HasColumnType("integer");

                    b.HasKey("CharacterSpecAbilityId", "ActionType", "Variant");

                    b.ToTable("CharacterSpecAbilityActionAssets", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbilityStat", b =>
                {
                    b.Property<Guid>("CharacterSpecAbilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("CharacterSpecAbilityId", "StatType");

                    b.ToTable("CharacterSpecAbilityStats", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PortraitUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CharacterSpecs", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpecActionAsset", b =>
                {
                    b.Property<Guid>("CharacterSpecId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<int>("Variant")
                        .HasColumnType("integer");

                    b.HasKey("CharacterSpecId", "ActionType", "Variant");

                    b.ToTable("CharacterSpecActionAssets", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpecStat", b =>
                {
                    b.Property<Guid>("CharacterSpecId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("CharacterSpecId", "StatType");

                    b.ToTable("CharacterSpecStats", "game");
                });

            modelBuilder.Entity("Domain.Game.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SpecId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SpecId");

                    b.ToTable("Characters", "game");
                });

            modelBuilder.Entity("Domain.Game.Characters.CharacterCodes.CharacterCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterCodes", "game");
                });

            modelBuilder.Entity("Domain.Game.Characters.CharacterTalents.CharacterTalent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("TalentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "TalentId")
                        .IsUnique();

                    b.ToTable("CharacterTalents", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.Enemy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Enemies", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer");

                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId", "Type")
                        .IsUnique();

                    b.ToTable("EnemyAbilities", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbilityActionAsset", b =>
                {
                    b.Property<Guid>("EnemyAbilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<int>("Variant")
                        .HasColumnType("integer");

                    b.HasKey("EnemyAbilityId", "ActionType", "Variant");

                    b.ToTable("EnemyAbilityActionAssets", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbilityStat", b =>
                {
                    b.Property<Guid>("EnemyAbilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("EnemyAbilityId", "StatType");

                    b.ToTable("EnemyAbilityStats", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyActionAsset", b =>
                {
                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<int>("Variant")
                        .HasColumnType("integer");

                    b.HasKey("EnemyId", "ActionType", "Variant");

                    b.ToTable("EnemyActionAssets", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyStat", b =>
                {
                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("EnemyId", "StatType");

                    b.ToTable("EnemyStats", "game");
                });

            modelBuilder.Entity("Domain.Game.ArenaItems.ArenaItem", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Sprite", b1 =>
                        {
                            b1.Property<Guid>("ArenaItemId")
                                .HasColumnType("uuid");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("ArenaItemId");

                            b1.ToTable("ArenaItems", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaItemId");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationArenaItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<float>("X")
                                        .HasColumnType("real");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real");

                                    b2.HasKey("SpriteAnimationArenaItemId");

                                    b2.ToTable("ArenaItems", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationArenaItemId");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Sprite")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Arenas.Arena", b =>
                {
                    b.OwnsMany("Domain.ValueObjects.Position", "BlockedPositions", b1 =>
                        {
                            b1.Property<Guid>("ArenaId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("ArenaId", "Id");

                            b1.ToTable("Arenas_BlockedPositions", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Position", "StartPosition", b1 =>
                        {
                            b1.Property<Guid>("ArenaId")
                                .HasColumnType("uuid");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("ArenaId");

                            b1.ToTable("Arenas", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaId");
                        });

                    b.Navigation("BlockedPositions");

                    b.Navigation("StartPosition")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaEnemies.ArenaEnemy", b =>
                {
                    b.HasOne("Domain.Game.Arenas.Arena", "Arena")
                        .WithMany("Enemies")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Game.Enemies.Enemy", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("ArenaEnemyId")
                                .HasColumnType("uuid");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("ArenaEnemyId");

                            b1.ToTable("ArenaEnemies", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaEnemyId");
                        });

                    b.Navigation("Arena");

                    b.Navigation("Enemy");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaPlacedItems.ArenaPlacedItem", b =>
                {
                    b.HasOne("Domain.Game.Arenas.Arena", "Arena")
                        .WithMany("Items")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Game.ArenaItems.ArenaItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("ArenaPlacedItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("ArenaPlacedItemId");

                            b1.ToTable("ArenaPlacedItems", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaPlacedItemId");
                        });

                    b.Navigation("Arena");

                    b.Navigation("Item");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaTerrainCells.ArenaTerrainCell", b =>
                {
                    b.HasOne("Domain.Game.Arenas.Arena", "Arena")
                        .WithMany("TerrainCells")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("ArenaTerrainCellId")
                                .HasColumnType("uuid");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("ArenaTerrainCellId");

                            b1.ToTable("ArenaTerrainCells", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaTerrainCellId");
                        });

                    b.Navigation("Arena");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecs.CharacterSpec", "CharacterSpec")
                        .WithMany("Abilities")
                        .HasForeignKey("CharacterSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSpec");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbilityActionAsset", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", "Ability")
                        .WithMany("ActionAssets")
                        .HasForeignKey("CharacterSpecAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Animation", b1 =>
                        {
                            b1.Property<Guid>("CharacterSpecAbilityActionAssetCharacterSpecAbilityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CharacterSpecAbilityActionAssetActionType")
                                .HasColumnType("integer");

                            b1.Property<int>("CharacterSpecAbilityActionAssetVariant")
                                .HasColumnType("integer");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("CharacterSpecAbilityActionAssetCharacterSpecAbilityId", "CharacterSpecAbilityActionAssetActionType", "CharacterSpecAbilityActionAssetVariant");

                            b1.ToTable("CharacterSpecAbilityActionAssets", "game");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSpecAbilityActionAssetCharacterSpecAbilityId", "CharacterSpecAbilityActionAssetActionType", "CharacterSpecAbilityActionAssetVariant");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationCharacterSpecAbilityActionAssetCharacterSpecAbilityId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("SpriteAnimationCharacterSpecAbilityActionAssetCharacterSpecAbi~");

                                    b2.Property<int>("SpriteAnimationCharacterSpecAbilityActionAssetActionType")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SpriteAnimationCharacterSpecAbilityActionAssetVariant")
                                        .HasColumnType("integer");

                                    b2.Property<float>("X")
                                        .HasColumnType("real");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real");

                                    b2.HasKey("SpriteAnimationCharacterSpecAbilityActionAssetCharacterSpecAbilityId", "SpriteAnimationCharacterSpecAbilityActionAssetActionType", "SpriteAnimationCharacterSpecAbilityActionAssetVariant");

                                    b2.ToTable("CharacterSpecAbilityActionAssets", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationCharacterSpecAbilityActionAssetCharacterSpecAbilityId", "SpriteAnimationCharacterSpecAbilityActionAssetActionType", "SpriteAnimationCharacterSpecAbilityActionAssetVariant");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Ability");

                    b.Navigation("Animation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbilityStat", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", "Ability")
                        .WithMany("Stats")
                        .HasForeignKey("CharacterSpecAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpec", b =>
                {
                    b.HasOne("Domain.Game.CharacterClasses.CharacterClass", "Class")
                        .WithMany("Specs")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpecActionAsset", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecs.CharacterSpec", "CharacterSpec")
                        .WithMany("ActionAssets")
                        .HasForeignKey("CharacterSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Animation", b1 =>
                        {
                            b1.Property<Guid>("CharacterSpecActionAssetCharacterSpecId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CharacterSpecActionAssetActionType")
                                .HasColumnType("integer");

                            b1.Property<int>("CharacterSpecActionAssetVariant")
                                .HasColumnType("integer");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("CharacterSpecActionAssetCharacterSpecId", "CharacterSpecActionAssetActionType", "CharacterSpecActionAssetVariant");

                            b1.ToTable("CharacterSpecActionAssets", "game");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSpecActionAssetCharacterSpecId", "CharacterSpecActionAssetActionType", "CharacterSpecActionAssetVariant");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationCharacterSpecActionAssetCharacterSpecId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("SpriteAnimationCharacterSpecActionAssetActionType")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SpriteAnimationCharacterSpecActionAssetVariant")
                                        .HasColumnType("integer");

                                    b2.Property<float>("X")
                                        .HasColumnType("real");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real");

                                    b2.HasKey("SpriteAnimationCharacterSpecActionAssetCharacterSpecId", "SpriteAnimationCharacterSpecActionAssetActionType", "SpriteAnimationCharacterSpecActionAssetVariant");

                                    b2.ToTable("CharacterSpecActionAssets", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationCharacterSpecActionAssetCharacterSpecId", "SpriteAnimationCharacterSpecActionAssetActionType", "SpriteAnimationCharacterSpecActionAssetVariant");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Animation")
                        .IsRequired();

                    b.Navigation("CharacterSpec");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpecStat", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecs.CharacterSpec", "CharacterSpec")
                        .WithMany("Stats")
                        .HasForeignKey("CharacterSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSpec");
                });

            modelBuilder.Entity("Domain.Game.Characters.Character", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecs.CharacterSpec", "Spec")
                        .WithMany("Characters")
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("Domain.Game.Characters.CharacterCodes.CharacterCode", b =>
                {
                    b.HasOne("Domain.Game.Characters.Character", null)
                        .WithMany("Codes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Characters.CharacterTalents.CharacterTalent", b =>
                {
                    b.HasOne("Domain.Game.Characters.Character", "Character")
                        .WithMany("Talents")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbility", b =>
                {
                    b.HasOne("Domain.Game.Enemies.Enemy", "Enemy")
                        .WithMany("Abilities")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbilityActionAsset", b =>
                {
                    b.HasOne("Domain.Game.Enemies.EnemyAbility", "Ability")
                        .WithMany("ActionAssets")
                        .HasForeignKey("EnemyAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Animation", b1 =>
                        {
                            b1.Property<Guid>("EnemyAbilityActionAssetEnemyAbilityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EnemyAbilityActionAssetActionType")
                                .HasColumnType("integer");

                            b1.Property<int>("EnemyAbilityActionAssetVariant")
                                .HasColumnType("integer");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("EnemyAbilityActionAssetEnemyAbilityId", "EnemyAbilityActionAssetActionType", "EnemyAbilityActionAssetVariant");

                            b1.ToTable("EnemyAbilityActionAssets", "game");

                            b1.WithOwner()
                                .HasForeignKey("EnemyAbilityActionAssetEnemyAbilityId", "EnemyAbilityActionAssetActionType", "EnemyAbilityActionAssetVariant");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationEnemyAbilityActionAssetEnemyAbilityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("SpriteAnimationEnemyAbilityActionAssetActionType")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SpriteAnimationEnemyAbilityActionAssetVariant")
                                        .HasColumnType("integer");

                                    b2.Property<float>("X")
                                        .HasColumnType("real");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real");

                                    b2.HasKey("SpriteAnimationEnemyAbilityActionAssetEnemyAbilityId", "SpriteAnimationEnemyAbilityActionAssetActionType", "SpriteAnimationEnemyAbilityActionAssetVariant");

                                    b2.ToTable("EnemyAbilityActionAssets", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationEnemyAbilityActionAssetEnemyAbilityId", "SpriteAnimationEnemyAbilityActionAssetActionType", "SpriteAnimationEnemyAbilityActionAssetVariant");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Ability");

                    b.Navigation("Animation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbilityStat", b =>
                {
                    b.HasOne("Domain.Game.Enemies.EnemyAbility", "Ability")
                        .WithMany("Stats")
                        .HasForeignKey("EnemyAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyActionAsset", b =>
                {
                    b.HasOne("Domain.Game.Enemies.Enemy", "Enemy")
                        .WithMany("ActionAssets")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Animation", b1 =>
                        {
                            b1.Property<Guid>("EnemyActionAssetEnemyId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EnemyActionAssetActionType")
                                .HasColumnType("integer");

                            b1.Property<int>("EnemyActionAssetVariant")
                                .HasColumnType("integer");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("EnemyActionAssetEnemyId", "EnemyActionAssetActionType", "EnemyActionAssetVariant");

                            b1.ToTable("EnemyActionAssets", "game");

                            b1.WithOwner()
                                .HasForeignKey("EnemyActionAssetEnemyId", "EnemyActionAssetActionType", "EnemyActionAssetVariant");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationEnemyActionAssetEnemyId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("SpriteAnimationEnemyActionAssetActionType")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SpriteAnimationEnemyActionAssetVariant")
                                        .HasColumnType("integer");

                                    b2.Property<float>("X")
                                        .HasColumnType("real");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real");

                                    b2.HasKey("SpriteAnimationEnemyActionAssetEnemyId", "SpriteAnimationEnemyActionAssetActionType", "SpriteAnimationEnemyActionAssetVariant");

                                    b2.ToTable("EnemyActionAssets", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationEnemyActionAssetEnemyId", "SpriteAnimationEnemyActionAssetActionType", "SpriteAnimationEnemyActionAssetVariant");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Animation")
                        .IsRequired();

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyStat", b =>
                {
                    b.HasOne("Domain.Game.Enemies.Enemy", "Enemy")
                        .WithMany("Stats")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("Domain.Game.Arenas.Arena", b =>
                {
                    b.Navigation("Enemies");

                    b.Navigation("Items");

                    b.Navigation("TerrainCells");
                });

            modelBuilder.Entity("Domain.Game.CharacterClasses.CharacterClass", b =>
                {
                    b.Navigation("Specs");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", b =>
                {
                    b.Navigation("ActionAssets");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpec", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("ActionAssets");

                    b.Navigation("Characters");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Domain.Game.Characters.Character", b =>
                {
                    b.Navigation("Codes");

                    b.Navigation("Talents");
                });

            modelBuilder.Entity("Domain.Game.Enemies.Enemy", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("ActionAssets");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbility", b =>
                {
                    b.Navigation("ActionAssets");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
