// <auto-generated />
using System;
using Infrastructure.Database.Game;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Game.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260511105542_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Game.ArenaItems.ArenaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_arena_items");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_arena_items_name");

                    b.ToTable("arena_items", "game");
                });

            modelBuilder.Entity("Domain.Game.Arenas.Arena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundAsset")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("background_asset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<int[]>("GameModes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("game_modes");

                    b.Property<int>("GridHeight")
                        .HasColumnType("integer")
                        .HasColumnName("grid_height");

                    b.Property<int>("GridWidth")
                        .HasColumnType("integer")
                        .HasColumnName("grid_width");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_arenas");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_arenas_name");

                    b.ToTable("arenas", "game");
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaEnemies.ArenaEnemy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uuid")
                        .HasColumnName("arena_id");

                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_id");

                    b.HasKey("Id")
                        .HasName("pk_arena_enemies");

                    b.HasIndex("ArenaId")
                        .HasDatabaseName("ix_arena_enemies_arena_id");

                    b.HasIndex("EnemyId")
                        .HasDatabaseName("ix_arena_enemies_enemy_id");

                    b.ToTable("arena_enemies", "game");
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaPlacedItems.ArenaPlacedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uuid")
                        .HasColumnName("arena_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("Id")
                        .HasName("pk_arena_placed_items");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_arena_placed_items_item_id");

                    b.HasIndex("ArenaId", "ItemId")
                        .HasDatabaseName("ix_arena_placed_items_arena_id_item_id");

                    b.ToTable("arena_placed_items", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterClasses.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_character_classes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_character_classes_name");

                    b.ToTable("character_classes", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterSpecId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_spec_id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer")
                        .HasColumnName("effect_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_character_spec_abilities");

                    b.HasIndex("CharacterSpecId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_character_spec_abilities_character_spec_id_type");

                    b.ToTable("character_spec_abilities", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbilityActionAsset", b =>
                {
                    b.Property<Guid>("CharacterSpecAbilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_spec_ability_id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<int>("Variant")
                        .HasColumnType("integer")
                        .HasColumnName("variant");

                    b.HasKey("CharacterSpecAbilityId", "ActionType", "Variant")
                        .HasName("pk_character_spec_ability_action_assets");

                    b.ToTable("character_spec_ability_action_assets", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbilityStat", b =>
                {
                    b.Property<Guid>("CharacterSpecAbilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_spec_ability_id");

                    b.Property<int>("StatType")
                        .HasColumnType("integer")
                        .HasColumnName("stat_type");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("CharacterSpecAbilityId", "StatType")
                        .HasName("pk_character_spec_ability_stats");

                    b.ToTable("character_spec_ability_stats", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<string>("PortraitUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("portrait_url");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_character_specs");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_character_specs_class_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_character_specs_name");

                    b.ToTable("character_specs", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpecActionAsset", b =>
                {
                    b.Property<Guid>("CharacterSpecId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_spec_id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<int>("Variant")
                        .HasColumnType("integer")
                        .HasColumnName("variant");

                    b.HasKey("CharacterSpecId", "ActionType", "Variant")
                        .HasName("pk_character_spec_action_assets");

                    b.ToTable("character_spec_action_assets", "game");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpecStat", b =>
                {
                    b.Property<Guid>("CharacterSpecId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_spec_id");

                    b.Property<int>("StatType")
                        .HasColumnType("integer")
                        .HasColumnName("stat_type");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("CharacterSpecId", "StatType")
                        .HasName("pk_character_spec_stats");

                    b.ToTable("character_spec_stats", "game");
                });

            modelBuilder.Entity("Domain.Game.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpecId")
                        .HasColumnType("uuid")
                        .HasColumnName("spec_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_name");

                    b.HasIndex("SpecId")
                        .HasDatabaseName("ix_characters_spec_id");

                    b.ToTable("characters", "game");
                });

            modelBuilder.Entity("Domain.Game.Characters.CharacterCodes.CharacterCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<string>("SourceCode")
                        .HasColumnType("text")
                        .HasColumnName("source_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_character_codes");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_character_codes_character_id");

                    b.ToTable("character_codes", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.Enemy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_enemies");

                    b.ToTable("enemies", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer")
                        .HasColumnName("effect_type");

                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_enemy_abilities");

                    b.HasIndex("EnemyId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_enemy_abilities_enemy_id_type");

                    b.ToTable("enemy_abilities", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbilityActionAsset", b =>
                {
                    b.Property<Guid>("EnemyAbilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_ability_id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<int>("Variant")
                        .HasColumnType("integer")
                        .HasColumnName("variant");

                    b.HasKey("EnemyAbilityId", "ActionType", "Variant")
                        .HasName("pk_enemy_ability_action_assets");

                    b.ToTable("enemy_ability_action_assets", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbilityStat", b =>
                {
                    b.Property<Guid>("EnemyAbilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_ability_id");

                    b.Property<int>("StatType")
                        .HasColumnType("integer")
                        .HasColumnName("stat_type");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("EnemyAbilityId", "StatType")
                        .HasName("pk_enemy_ability_stats");

                    b.ToTable("enemy_ability_stats", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyActionAsset", b =>
                {
                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<int>("Variant")
                        .HasColumnType("integer")
                        .HasColumnName("variant");

                    b.HasKey("EnemyId", "ActionType", "Variant")
                        .HasName("pk_enemy_action_assets");

                    b.ToTable("enemy_action_assets", "game");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyStat", b =>
                {
                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_id");

                    b.Property<int>("StatType")
                        .HasColumnType("integer")
                        .HasColumnName("stat_type");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("EnemyId", "StatType")
                        .HasName("pk_enemy_stats");

                    b.ToTable("enemy_stats", "game");
                });

            modelBuilder.Entity("Domain.Game.ArenaItems.ArenaItem", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Sprite", b1 =>
                        {
                            b1.Property<Guid>("ArenaItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real")
                                .HasColumnName("sprite_animation_speed");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer")
                                .HasColumnName("sprite_frame_count");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("sprite_url");

                            b1.HasKey("ArenaItemId");

                            b1.ToTable("arena_items", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaItemId")
                                .HasConstraintName("fk_arena_items_arena_items_id");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationArenaItemId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<float>("X")
                                        .HasColumnType("real")
                                        .HasColumnName("sprite_scale_x");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real")
                                        .HasColumnName("sprite_scale_y");

                                    b2.HasKey("SpriteAnimationArenaItemId");

                                    b2.ToTable("arena_items", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationArenaItemId")
                                        .HasConstraintName("fk_arena_items_arena_items_id");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Sprite")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Arenas.Arena", b =>
                {
                    b.OwnsMany("Domain.ValueObjects.Position", "BlockedPositions", b1 =>
                        {
                            b1.Property<Guid>("ArenaId")
                                .HasColumnType("uuid")
                                .HasColumnName("arena_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("x");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("y");

                            b1.HasKey("ArenaId", "Id")
                                .HasName("pk_arenas_blocked_positions");

                            b1.ToTable("arenas_blocked_positions", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaId")
                                .HasConstraintName("fk_arenas_blocked_positions_arenas_arena_id");
                        });

                    b.OwnsOne("Domain.ValueObjects.Position", "StartPosition", b1 =>
                        {
                            b1.Property<Guid>("ArenaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("start_position_x");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("start_position_y");

                            b1.HasKey("ArenaId");

                            b1.ToTable("arenas", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaId")
                                .HasConstraintName("fk_arenas_arenas_id");
                        });

                    b.Navigation("BlockedPositions");

                    b.Navigation("StartPosition")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaEnemies.ArenaEnemy", b =>
                {
                    b.HasOne("Domain.Game.Arenas.Arena", "Arena")
                        .WithMany("Enemies")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arena_enemies_arenas_arena_id");

                    b.HasOne("Domain.Game.Enemies.Enemy", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arena_enemies_enemies_enemy_id");

                    b.OwnsOne("Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("ArenaEnemyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("position_x");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("position_y");

                            b1.HasKey("ArenaEnemyId");

                            b1.ToTable("arena_enemies", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaEnemyId")
                                .HasConstraintName("fk_arena_enemies_arena_enemies_id");
                        });

                    b.Navigation("Arena");

                    b.Navigation("Enemy");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Arenas.ArenaPlacedItems.ArenaPlacedItem", b =>
                {
                    b.HasOne("Domain.Game.Arenas.Arena", "Arena")
                        .WithMany("Items")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arena_placed_items_arenas_arena_id");

                    b.HasOne("Domain.Game.ArenaItems.ArenaItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_arena_placed_items_arena_items_item_id");

                    b.OwnsOne("Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("ArenaPlacedItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("position_x");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("position_y");

                            b1.HasKey("ArenaPlacedItemId");

                            b1.ToTable("arena_placed_items", "game");

                            b1.WithOwner()
                                .HasForeignKey("ArenaPlacedItemId")
                                .HasConstraintName("fk_arena_placed_items_arena_placed_items_id");
                        });

                    b.Navigation("Arena");

                    b.Navigation("Item");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecs.CharacterSpec", "CharacterSpec")
                        .WithMany("Abilities")
                        .HasForeignKey("CharacterSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_spec_abilities_character_specs_character_spec_id");

                    b.Navigation("CharacterSpec");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbilityActionAsset", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", "Ability")
                        .WithMany("ActionAssets")
                        .HasForeignKey("CharacterSpecAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_spec_ability_action_assets_character_spec_abiliti");

                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Animation", b1 =>
                        {
                            b1.Property<Guid>("CharacterSpecAbilityActionAssetCharacterSpecAbilityId")
                                .HasColumnType("uuid")
                                .HasColumnName("character_spec_ability_id");

                            b1.Property<int>("CharacterSpecAbilityActionAssetActionType")
                                .HasColumnType("integer")
                                .HasColumnName("action_type");

                            b1.Property<int>("CharacterSpecAbilityActionAssetVariant")
                                .HasColumnType("integer")
                                .HasColumnName("variant");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real")
                                .HasColumnName("animation_animation_speed");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer")
                                .HasColumnName("animation_frame_count");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("animation_url");

                            b1.HasKey("CharacterSpecAbilityActionAssetCharacterSpecAbilityId", "CharacterSpecAbilityActionAssetActionType", "CharacterSpecAbilityActionAssetVariant");

                            b1.ToTable("character_spec_ability_action_assets", "game");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSpecAbilityActionAssetCharacterSpecAbilityId", "CharacterSpecAbilityActionAssetActionType", "CharacterSpecAbilityActionAssetVariant")
                                .HasConstraintName("fk_character_spec_ability_action_assets_character_spec_ability");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationCharacterSpecAbilityActionAssetCharacterSpecAbilityId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("character_spec_ability_id");

                                    b2.Property<int>("SpriteAnimationCharacterSpecAbilityActionAssetActionType")
                                        .HasColumnType("integer")
                                        .HasColumnName("action_type");

                                    b2.Property<int>("SpriteAnimationCharacterSpecAbilityActionAssetVariant")
                                        .HasColumnType("integer")
                                        .HasColumnName("variant");

                                    b2.Property<float>("X")
                                        .HasColumnType("real")
                                        .HasColumnName("animation_scale_x");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real")
                                        .HasColumnName("animation_scale_y");

                                    b2.HasKey("SpriteAnimationCharacterSpecAbilityActionAssetCharacterSpecAbilityId", "SpriteAnimationCharacterSpecAbilityActionAssetActionType", "SpriteAnimationCharacterSpecAbilityActionAssetVariant");

                                    b2.ToTable("character_spec_ability_action_assets", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationCharacterSpecAbilityActionAssetCharacterSpecAbilityId", "SpriteAnimationCharacterSpecAbilityActionAssetActionType", "SpriteAnimationCharacterSpecAbilityActionAssetVariant")
                                        .HasConstraintName("fk_character_spec_ability_action_assets_character_spec_ability");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Ability");

                    b.Navigation("Animation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbilityStat", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", "Ability")
                        .WithMany("Stats")
                        .HasForeignKey("CharacterSpecAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_spec_ability_stats_character_spec_abilities_chara");

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpec", b =>
                {
                    b.HasOne("Domain.Game.CharacterClasses.CharacterClass", "Class")
                        .WithMany("Specs")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_specs_character_classes_class_id");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpecActionAsset", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecs.CharacterSpec", "CharacterSpec")
                        .WithMany("ActionAssets")
                        .HasForeignKey("CharacterSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_spec_action_assets_character_specs_character_spec");

                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Animation", b1 =>
                        {
                            b1.Property<Guid>("CharacterSpecActionAssetCharacterSpecId")
                                .HasColumnType("uuid")
                                .HasColumnName("character_spec_id");

                            b1.Property<int>("CharacterSpecActionAssetActionType")
                                .HasColumnType("integer")
                                .HasColumnName("action_type");

                            b1.Property<int>("CharacterSpecActionAssetVariant")
                                .HasColumnType("integer")
                                .HasColumnName("variant");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real")
                                .HasColumnName("animation_animation_speed");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer")
                                .HasColumnName("animation_frame_count");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("animation_url");

                            b1.HasKey("CharacterSpecActionAssetCharacterSpecId", "CharacterSpecActionAssetActionType", "CharacterSpecActionAssetVariant");

                            b1.ToTable("character_spec_action_assets", "game");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSpecActionAssetCharacterSpecId", "CharacterSpecActionAssetActionType", "CharacterSpecActionAssetVariant")
                                .HasConstraintName("fk_character_spec_action_assets_character_spec_action_assets_c");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationCharacterSpecActionAssetCharacterSpecId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("character_spec_id");

                                    b2.Property<int>("SpriteAnimationCharacterSpecActionAssetActionType")
                                        .HasColumnType("integer")
                                        .HasColumnName("action_type");

                                    b2.Property<int>("SpriteAnimationCharacterSpecActionAssetVariant")
                                        .HasColumnType("integer")
                                        .HasColumnName("variant");

                                    b2.Property<float>("X")
                                        .HasColumnType("real")
                                        .HasColumnName("animation_scale_x");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real")
                                        .HasColumnName("animation_scale_y");

                                    b2.HasKey("SpriteAnimationCharacterSpecActionAssetCharacterSpecId", "SpriteAnimationCharacterSpecActionAssetActionType", "SpriteAnimationCharacterSpecActionAssetVariant");

                                    b2.ToTable("character_spec_action_assets", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationCharacterSpecActionAssetCharacterSpecId", "SpriteAnimationCharacterSpecActionAssetActionType", "SpriteAnimationCharacterSpecActionAssetVariant")
                                        .HasConstraintName("fk_character_spec_action_assets_character_spec_action_assets_c");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Animation")
                        .IsRequired();

                    b.Navigation("CharacterSpec");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpecStat", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecs.CharacterSpec", "CharacterSpec")
                        .WithMany("Stats")
                        .HasForeignKey("CharacterSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_spec_stats_character_specs_character_spec_id");

                    b.Navigation("CharacterSpec");
                });

            modelBuilder.Entity("Domain.Game.Characters.Character", b =>
                {
                    b.HasOne("Domain.Game.CharacterSpecs.CharacterSpec", "Spec")
                        .WithMany("Characters")
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_character_specs_spec_id");

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("Domain.Game.Characters.CharacterCodes.CharacterCode", b =>
                {
                    b.HasOne("Domain.Game.Characters.Character", null)
                        .WithMany("Codes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_codes_characters_character_id");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbility", b =>
                {
                    b.HasOne("Domain.Game.Enemies.Enemy", "Enemy")
                        .WithMany("Abilities")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_abilities_enemies_enemy_id");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbilityActionAsset", b =>
                {
                    b.HasOne("Domain.Game.Enemies.EnemyAbility", "Ability")
                        .WithMany("ActionAssets")
                        .HasForeignKey("EnemyAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_ability_action_assets_enemy_abilities_enemy_ability_id");

                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Animation", b1 =>
                        {
                            b1.Property<Guid>("EnemyAbilityActionAssetEnemyAbilityId")
                                .HasColumnType("uuid")
                                .HasColumnName("enemy_ability_id");

                            b1.Property<int>("EnemyAbilityActionAssetActionType")
                                .HasColumnType("integer")
                                .HasColumnName("action_type");

                            b1.Property<int>("EnemyAbilityActionAssetVariant")
                                .HasColumnType("integer")
                                .HasColumnName("variant");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real")
                                .HasColumnName("animation_animation_speed");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer")
                                .HasColumnName("animation_frame_count");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("animation_url");

                            b1.HasKey("EnemyAbilityActionAssetEnemyAbilityId", "EnemyAbilityActionAssetActionType", "EnemyAbilityActionAssetVariant");

                            b1.ToTable("enemy_ability_action_assets", "game");

                            b1.WithOwner()
                                .HasForeignKey("EnemyAbilityActionAssetEnemyAbilityId", "EnemyAbilityActionAssetActionType", "EnemyAbilityActionAssetVariant")
                                .HasConstraintName("fk_enemy_ability_action_assets_enemy_ability_action_assets_ene");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationEnemyAbilityActionAssetEnemyAbilityId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("enemy_ability_id");

                                    b2.Property<int>("SpriteAnimationEnemyAbilityActionAssetActionType")
                                        .HasColumnType("integer")
                                        .HasColumnName("action_type");

                                    b2.Property<int>("SpriteAnimationEnemyAbilityActionAssetVariant")
                                        .HasColumnType("integer")
                                        .HasColumnName("variant");

                                    b2.Property<float>("X")
                                        .HasColumnType("real")
                                        .HasColumnName("animation_scale_x");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real")
                                        .HasColumnName("animation_scale_y");

                                    b2.HasKey("SpriteAnimationEnemyAbilityActionAssetEnemyAbilityId", "SpriteAnimationEnemyAbilityActionAssetActionType", "SpriteAnimationEnemyAbilityActionAssetVariant");

                                    b2.ToTable("enemy_ability_action_assets", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationEnemyAbilityActionAssetEnemyAbilityId", "SpriteAnimationEnemyAbilityActionAssetActionType", "SpriteAnimationEnemyAbilityActionAssetVariant")
                                        .HasConstraintName("fk_enemy_ability_action_assets_enemy_ability_action_assets_ene");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Ability");

                    b.Navigation("Animation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbilityStat", b =>
                {
                    b.HasOne("Domain.Game.Enemies.EnemyAbility", "Ability")
                        .WithMany("Stats")
                        .HasForeignKey("EnemyAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_ability_stats_enemy_abilities_enemy_ability_id");

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyActionAsset", b =>
                {
                    b.HasOne("Domain.Game.Enemies.Enemy", "Enemy")
                        .WithMany("ActionAssets")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_action_assets_enemies_enemy_id");

                    b.OwnsOne("Domain.ValueObjects.SpriteAnimation", "Animation", b1 =>
                        {
                            b1.Property<Guid>("EnemyActionAssetEnemyId")
                                .HasColumnType("uuid")
                                .HasColumnName("enemy_id");

                            b1.Property<int>("EnemyActionAssetActionType")
                                .HasColumnType("integer")
                                .HasColumnName("action_type");

                            b1.Property<int>("EnemyActionAssetVariant")
                                .HasColumnType("integer")
                                .HasColumnName("variant");

                            b1.Property<float>("AnimationSpeed")
                                .HasColumnType("real")
                                .HasColumnName("animation_animation_speed");

                            b1.Property<int>("FrameCount")
                                .HasColumnType("integer")
                                .HasColumnName("animation_frame_count");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("animation_url");

                            b1.HasKey("EnemyActionAssetEnemyId", "EnemyActionAssetActionType", "EnemyActionAssetVariant");

                            b1.ToTable("enemy_action_assets", "game");

                            b1.WithOwner()
                                .HasForeignKey("EnemyActionAssetEnemyId", "EnemyActionAssetActionType", "EnemyActionAssetVariant")
                                .HasConstraintName("fk_enemy_action_assets_enemy_action_assets_enemy_id_action_typ");

                            b1.OwnsOne("Domain.ValueObjects.Scale", "Scale", b2 =>
                                {
                                    b2.Property<Guid>("SpriteAnimationEnemyActionAssetEnemyId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("enemy_id");

                                    b2.Property<int>("SpriteAnimationEnemyActionAssetActionType")
                                        .HasColumnType("integer")
                                        .HasColumnName("action_type");

                                    b2.Property<int>("SpriteAnimationEnemyActionAssetVariant")
                                        .HasColumnType("integer")
                                        .HasColumnName("variant");

                                    b2.Property<float>("X")
                                        .HasColumnType("real")
                                        .HasColumnName("animation_scale_x");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real")
                                        .HasColumnName("animation_scale_y");

                                    b2.HasKey("SpriteAnimationEnemyActionAssetEnemyId", "SpriteAnimationEnemyActionAssetActionType", "SpriteAnimationEnemyActionAssetVariant");

                                    b2.ToTable("enemy_action_assets", "game");

                                    b2.WithOwner()
                                        .HasForeignKey("SpriteAnimationEnemyActionAssetEnemyId", "SpriteAnimationEnemyActionAssetActionType", "SpriteAnimationEnemyActionAssetVariant")
                                        .HasConstraintName("fk_enemy_action_assets_enemy_action_assets_enemy_id_action_typ");
                                });

                            b1.Navigation("Scale")
                                .IsRequired();
                        });

                    b.Navigation("Animation")
                        .IsRequired();

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyStat", b =>
                {
                    b.HasOne("Domain.Game.Enemies.Enemy", "Enemy")
                        .WithMany("Stats")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_stats_enemies_enemy_id");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("Domain.Game.Arenas.Arena", b =>
                {
                    b.Navigation("Enemies");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Game.CharacterClasses.CharacterClass", b =>
                {
                    b.Navigation("Specs");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecAbilities.CharacterSpecAbility", b =>
                {
                    b.Navigation("ActionAssets");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Domain.Game.CharacterSpecs.CharacterSpec", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("ActionAssets");

                    b.Navigation("Characters");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Domain.Game.Characters.Character", b =>
                {
                    b.Navigation("Codes");
                });

            modelBuilder.Entity("Domain.Game.Enemies.Enemy", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("ActionAssets");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Domain.Game.Enemies.EnemyAbility", b =>
                {
                    b.Navigation("ActionAssets");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
