<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Chronicles\Chronicles.Application\Chronicles.Application.csproj" />
    <ProjectReference Include="..\..\src\Chronicles\Chronicles.Domain\Chronicles.Domain.csproj" />
    <ProjectReference Include="..\..\src\Chronicles\Chronicles.Infrastructure\Chronicles.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\GameRuntime\GameRuntime.Common\GameRuntime.Common.csproj" />
    <ProjectReference Include="..\..\src\GameRuntime\GameRuntime.Logic.User.Api\GameRuntime.Logic.User.Api.csproj" />
    <ProjectReference Include="..\..\src\GameRuntime\GameRuntime\GameRuntime.csproj" />
    <ProjectReference Include="..\..\src\IntegrationContracts\IntegrationContracts.csproj" />
    <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Web.Api\Web.Api.csproj" />
  </ItemGroup>

</Project>
