// <auto-generated />
using Chronicles.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chronicles.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ChroniclesDbContext))]
    partial class ChroniclesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chronicles")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chronicles.Domain.CharacterChronicleStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BattlesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("battles_played");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("character_name");

                    b.Property<int>("Defeats")
                        .HasColumnType("integer")
                        .HasColumnName("defeats");

                    b.Property<int>("Draws")
                        .HasColumnType("integer")
                        .HasColumnName("draws");

                    b.Property<DateTime?>("LastSessionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_session_at_utc");

                    b.Property<int>("TotalTurnsPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("total_turns_played");

                    b.Property<int>("Victories")
                        .HasColumnType("integer")
                        .HasColumnName("victories");

                    b.HasKey("Id")
                        .HasName("pk_character_chronicle_stats");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_chronicle_stats_character_id");

                    b.ToTable("character_chronicle_stats", "chronicles");
                });

            modelBuilder.Entity("Chronicles.Domain.CharacterNominationScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("character_name");

                    b.Property<string>("CharacterClassName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("character_class_name");

                    b.Property<string>("CharacterSpecName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("character_spec_name");

                    b.Property<int>("NominationType")
                        .HasColumnType("integer")
                        .HasColumnName("nomination_type");

                    b.Property<DateTime?>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_first_name");

                    b.Property<string>("UserLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_last_name");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_character_nomination_scores");

                    b.HasIndex("NominationType", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_nomination_scores_nomination_type_character_id");

                    b.HasIndex("NominationType", "Value")
                        .HasDatabaseName("ix_character_nomination_scores_nomination_type_value");

                    b.ToTable("character_nomination_scores", "chronicles");
                });

            modelBuilder.Entity("Chronicles.Domain.ChronicleNomination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("MetricLabel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("metric_label");

                    b.Property<string>("MetricUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric_unit");

                    b.Property<int>("SortDirection")
                        .HasColumnType("integer")
                        .HasColumnName("sort_direction");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("ValueKind")
                        .HasColumnType("integer")
                        .HasColumnName("value_kind");

                    b.HasKey("Id")
                        .HasName("pk_chronicle_nominations");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("ix_chronicle_nominations_type");

                    b.ToTable("chronicle_nominations", "chronicles");
                });

            modelBuilder.Entity("Chronicles.Domain.ChronicleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("character_name");

                    b.Property<string>("CharacterClassName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("character_class_name");

                    b.Property<string>("CharacterSpecName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("character_spec_name");

                    b.Property<int>("NominationType")
                        .HasColumnType("integer")
                        .HasColumnName("nomination_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("UserFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_first_name");

                    b.Property<string>("UserLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_last_name");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_chronicle_records");

                    b.HasIndex("NominationType", "Value")
                        .HasDatabaseName("ix_chronicle_records_nomination_type_value");

                    b.HasIndex("SessionId", "NominationType", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_chronicle_records_session_id_nomination_type_character_id");

                    b.ToTable("chronicle_records", "chronicles");
                });

            modelBuilder.Entity("Chronicles.Domain.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAtUtc", "DeadLetteredAtUtc", "NextAttemptAtUtc", "ReceivedAtUtc")
                        .HasDatabaseName("ix_inbox_messages_processing_queue");

                    b.ToTable("inbox_messages", "chronicles");
                });

            modelBuilder.Entity("Chronicles.Infrastructure.Outbox.OutboxImportCursor", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("LastMessageCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_created_at_utc");

                    b.Property<Guid>("LastMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_message_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Name")
                        .HasName("pk_import_cursors");

                    b.ToTable("import_cursors", "chronicles");
                });
#pragma warning restore 612, 618
        }
    }
}
