// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database.GameRuntime;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.GameRuntime.Migrations
{
    [DbContext(typeof(GameRuntimeDbContext))]
    [Migration("20251206152506_WinnerUnitId")]
    partial class WinnerUnitId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game_runtime")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.GameRuntime.GameSessionParticipants.GameSessionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_game_session_participants");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_game_session_participants_session_id");

                    b.ToTable("game_session_participants", "game_runtime");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessions.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uuid")
                        .HasColumnName("arena_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("error_message");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalTurns")
                        .HasColumnType("integer")
                        .HasColumnName("total_turns");

                    b.PrimitiveCollection<List<Guid>>("UserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("user_ids");

                    b.HasKey("Id")
                        .HasName("pk_game_sessions");

                    b.ToTable("game_sessions", "game_runtime");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessionParticipants.GameSessionParticipant", b =>
                {
                    b.HasOne("Domain.GameRuntime.GameSessions.GameSession", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_session_participants_game_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessions.GameSession", b =>
                {
                    b.OwnsOne("Domain.GameRuntime.GameResults.GameResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("GameSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Outcome")
                                .HasColumnType("integer")
                                .HasColumnName("result_outcome");

                            b1.Property<Guid?>("WinnerUnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("result_winner_unit_id");

                            b1.HasKey("GameSessionId");

                            b1.ToTable("game_sessions", "game_runtime");

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId")
                                .HasConstraintName("fk_game_sessions_game_sessions_id");
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessions.GameSession", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
