// <auto-generated>
//     Создано командой dotnet ef migrations add.
// </auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.GameRuntime.Migrations
{
    /// <inheritdoc />
    public partial class SlavicReworkLogs : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_game_action_log_entries_game_sessions_session_id",
                schema: "game_runtime",
                table: "game_action_log_entries");

            migrationBuilder.DropForeignKey(
                name: "fk_game_session_participants_game_sessions_session_id",
                schema: "game_runtime",
                table: "game_session_participants");

            migrationBuilder.DropPrimaryKey(
                name: "pk_outbox_messages",
                schema: "integration",
                table: "outbox_messages");

            migrationBuilder.DropPrimaryKey(
                name: "pk_game_sessions",
                schema: "game_runtime",
                table: "game_sessions");

            migrationBuilder.DropPrimaryKey(
                name: "pk_game_session_participants",
                schema: "game_runtime",
                table: "game_session_participants");

            migrationBuilder.DropPrimaryKey(
                name: "pk_game_action_log_entries",
                schema: "game_runtime",
                table: "game_action_log_entries");

            migrationBuilder.RenameTable(
                name: "game_sessions",
                schema: "game_runtime",
                newName: "GameSessions",
                newSchema: "game_runtime");

            migrationBuilder.RenameTable(
                name: "game_session_participants",
                schema: "game_runtime",
                newName: "GameSessionParticipants",
                newSchema: "game_runtime");

            migrationBuilder.RenameTable(
                name: "game_action_log_entries",
                schema: "game_runtime",
                newName: "GameActionLogEntries",
                newSchema: "game_runtime");

            migrationBuilder.RenameColumn(
                name: "type",
                schema: "integration",
                table: "outbox_messages",
                newName: "Type");

            migrationBuilder.RenameColumn(
                name: "payload",
                schema: "integration",
                table: "outbox_messages",
                newName: "Payload");

            migrationBuilder.RenameColumn(
                name: "error",
                schema: "integration",
                table: "outbox_messages",
                newName: "Error");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "integration",
                table: "outbox_messages",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "processed_at_utc",
                schema: "integration",
                table: "outbox_messages",
                newName: "ProcessedAtUtc");

            migrationBuilder.RenameColumn(
                name: "occurred_at_utc",
                schema: "integration",
                table: "outbox_messages",
                newName: "OccurredAtUtc");

            migrationBuilder.RenameColumn(
                name: "created_at_utc",
                schema: "integration",
                table: "outbox_messages",
                newName: "CreatedAtUtc");

            migrationBuilder.RenameColumn(
                name: "aggregate_id",
                schema: "integration",
                table: "outbox_messages",
                newName: "AggregateId");

            migrationBuilder.RenameIndex(
                name: "ix_outbox_messages_type_created_at_utc_id",
                schema: "integration",
                table: "outbox_messages",
                newName: "IX_outbox_messages_Type_CreatedAtUtc_Id");

            migrationBuilder.RenameIndex(
                name: "ix_outbox_messages_aggregate_id_type",
                schema: "integration",
                table: "outbox_messages",
                newName: "IX_outbox_messages_AggregateId_Type");

            migrationBuilder.RenameColumn(
                name: "status",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "Status");

            migrationBuilder.RenameColumn(
                name: "result_outcome",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "Result_Outcome");

            migrationBuilder.RenameColumn(
                name: "mode",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "Mode");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "user_ids",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "UserIds");

            migrationBuilder.RenameColumn(
                name: "total_turns",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "TotalTurns");

            migrationBuilder.RenameColumn(
                name: "started_at",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "StartedAt");

            migrationBuilder.RenameColumn(
                name: "error_message",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "ErrorMessage");

            migrationBuilder.RenameColumn(
                name: "ended_at",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "EndedAt");

            migrationBuilder.RenameColumn(
                name: "arena_id",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "ArenaId");

            migrationBuilder.RenameColumn(
                name: "result_winner_unit_id",
                schema: "game_runtime",
                table: "GameSessions",
                newName: "Result_WinnerUnitId");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "user_last_name",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "UserLastName");

            migrationBuilder.RenameColumn(
                name: "user_id",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "UserId");

            migrationBuilder.RenameColumn(
                name: "user_first_name",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "UserFirstName");

            migrationBuilder.RenameColumn(
                name: "unit_type",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "UnitType");

            migrationBuilder.RenameColumn(
                name: "unit_name",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "UnitName");

            migrationBuilder.RenameColumn(
                name: "unit_id",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "UnitId");

            migrationBuilder.RenameColumn(
                name: "session_id",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "SessionId");

            migrationBuilder.RenameColumn(
                name: "joined_at",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "JoinedAt");

            migrationBuilder.RenameColumn(
                name: "character_spec_name",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "CharacterSpecName");

            migrationBuilder.RenameColumn(
                name: "character_class_name",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "CharacterClassName");

            migrationBuilder.RenameIndex(
                name: "ix_game_session_participants_session_id",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                newName: "IX_GameSessionParticipants_SessionId");

            migrationBuilder.RenameColumn(
                name: "value",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "Value");

            migrationBuilder.RenameColumn(
                name: "to_y",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "To_Y");

            migrationBuilder.RenameColumn(
                name: "to_x",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "To_X");

            migrationBuilder.RenameColumn(
                name: "position_y",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "Position_Y");

            migrationBuilder.RenameColumn(
                name: "position_x",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "Position_X");

            migrationBuilder.RenameColumn(
                name: "info",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "Info");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "walk_log_entry_facing_direction",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "WalkLogEntry_FacingDirection");

            migrationBuilder.RenameColumn(
                name: "turn_index",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "TurnIndex");

            migrationBuilder.RenameColumn(
                name: "target_name",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "TargetName");

            migrationBuilder.RenameColumn(
                name: "target_id",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "TargetId");

            migrationBuilder.RenameColumn(
                name: "session_id",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "SessionId");

            migrationBuilder.RenameColumn(
                name: "placed_item_id",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "PlacedItemId");

            migrationBuilder.RenameColumn(
                name: "item_type",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "ItemType");

            migrationBuilder.RenameColumn(
                name: "item_picked_up_log_entry_value",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "ItemPickedUpLogEntry_Value");

            migrationBuilder.RenameColumn(
                name: "item_name",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "ItemName");

            migrationBuilder.RenameColumn(
                name: "item_id",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "ItemId");

            migrationBuilder.RenameColumn(
                name: "facing_direction",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "FacingDirection");

            migrationBuilder.RenameColumn(
                name: "entry_type",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "EntryType");

            migrationBuilder.RenameColumn(
                name: "effect_type",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "EffectType");

            migrationBuilder.RenameColumn(
                name: "created_at",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "CreatedAt");

            migrationBuilder.RenameColumn(
                name: "actor_name",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "ActorName");

            migrationBuilder.RenameColumn(
                name: "actor_id",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "ActorId");

            migrationBuilder.RenameColumn(
                name: "ability_type",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "AbilityType");

            migrationBuilder.RenameColumn(
                name: "ability_name",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "AbilityName");

            migrationBuilder.RenameColumn(
                name: "target_hp_max",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "TargetHp_Max");

            migrationBuilder.RenameColumn(
                name: "target_hp_current",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "TargetHp_Current");

            migrationBuilder.RenameColumn(
                name: "actor_hp_max",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "StatSnapshot_TargetHp_Max");

            migrationBuilder.RenameColumn(
                name: "actor_hp_current",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "StatSnapshot_TargetHp_Current");

            migrationBuilder.RenameIndex(
                name: "ix_game_action_log_entries_session_id",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                newName: "IX_GameActionLogEntries_SessionId");

            migrationBuilder.AddColumn<decimal>(
                name: "ActorHp_Current",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                type: "numeric",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "ActorHp_Max",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                type: "numeric",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Duration",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "Magnitude",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                type: "numeric",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Path",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "RoundNumber",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "StatusAppliedLogEntry_TargetId",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "StatusAppliedLogEntry_TargetName",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                type: "character varying(32)",
                maxLength: 32,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "StatusType",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                type: "integer",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_outbox_messages",
                schema: "integration",
                table: "outbox_messages",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_GameSessions",
                schema: "game_runtime",
                table: "GameSessions",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_GameSessionParticipants",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_GameActionLogEntries",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_GameActionLogEntries_GameSessions_SessionId",
                schema: "game_runtime",
                table: "GameActionLogEntries",
                column: "SessionId",
                principalSchema: "game_runtime",
                principalTable: "GameSessions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_GameSessionParticipants_GameSessions_SessionId",
                schema: "game_runtime",
                table: "GameSessionParticipants",
                column: "SessionId",
                principalSchema: "game_runtime",
                principalTable: "GameSessions",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_GameActionLogEntries_GameSessions_SessionId",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropForeignKey(
                name: "FK_GameSessionParticipants_GameSessions_SessionId",
                schema: "game_runtime",
                table: "GameSessionParticipants");

            migrationBuilder.DropPrimaryKey(
                name: "PK_outbox_messages",
                schema: "integration",
                table: "outbox_messages");

            migrationBuilder.DropPrimaryKey(
                name: "PK_GameSessions",
                schema: "game_runtime",
                table: "GameSessions");

            migrationBuilder.DropPrimaryKey(
                name: "PK_GameSessionParticipants",
                schema: "game_runtime",
                table: "GameSessionParticipants");

            migrationBuilder.DropPrimaryKey(
                name: "PK_GameActionLogEntries",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropColumn(
                name: "ActorHp_Current",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropColumn(
                name: "ActorHp_Max",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropColumn(
                name: "Duration",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropColumn(
                name: "Magnitude",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropColumn(
                name: "Path",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropColumn(
                name: "RoundNumber",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropColumn(
                name: "StatusAppliedLogEntry_TargetId",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropColumn(
                name: "StatusAppliedLogEntry_TargetName",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.DropColumn(
                name: "StatusType",
                schema: "game_runtime",
                table: "GameActionLogEntries");

            migrationBuilder.RenameTable(
                name: "GameSessions",
                schema: "game_runtime",
                newName: "game_sessions",
                newSchema: "game_runtime");

            migrationBuilder.RenameTable(
                name: "GameSessionParticipants",
                schema: "game_runtime",
                newName: "game_session_participants",
                newSchema: "game_runtime");

            migrationBuilder.RenameTable(
                name: "GameActionLogEntries",
                schema: "game_runtime",
                newName: "game_action_log_entries",
                newSchema: "game_runtime");

            migrationBuilder.RenameColumn(
                name: "Type",
                schema: "integration",
                table: "outbox_messages",
                newName: "type");

            migrationBuilder.RenameColumn(
                name: "Payload",
                schema: "integration",
                table: "outbox_messages",
                newName: "payload");

            migrationBuilder.RenameColumn(
                name: "Error",
                schema: "integration",
                table: "outbox_messages",
                newName: "error");

            migrationBuilder.RenameColumn(
                name: "Id",
                schema: "integration",
                table: "outbox_messages",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "ProcessedAtUtc",
                schema: "integration",
                table: "outbox_messages",
                newName: "processed_at_utc");

            migrationBuilder.RenameColumn(
                name: "OccurredAtUtc",
                schema: "integration",
                table: "outbox_messages",
                newName: "occurred_at_utc");

            migrationBuilder.RenameColumn(
                name: "CreatedAtUtc",
                schema: "integration",
                table: "outbox_messages",
                newName: "created_at_utc");

            migrationBuilder.RenameColumn(
                name: "AggregateId",
                schema: "integration",
                table: "outbox_messages",
                newName: "aggregate_id");

            migrationBuilder.RenameIndex(
                name: "IX_outbox_messages_Type_CreatedAtUtc_Id",
                schema: "integration",
                table: "outbox_messages",
                newName: "ix_outbox_messages_type_created_at_utc_id");

            migrationBuilder.RenameIndex(
                name: "IX_outbox_messages_AggregateId_Type",
                schema: "integration",
                table: "outbox_messages",
                newName: "ix_outbox_messages_aggregate_id_type");

            migrationBuilder.RenameColumn(
                name: "Status",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "status");

            migrationBuilder.RenameColumn(
                name: "Result_Outcome",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "result_outcome");

            migrationBuilder.RenameColumn(
                name: "Mode",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "mode");

            migrationBuilder.RenameColumn(
                name: "Id",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserIds",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "user_ids");

            migrationBuilder.RenameColumn(
                name: "TotalTurns",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "total_turns");

            migrationBuilder.RenameColumn(
                name: "StartedAt",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "started_at");

            migrationBuilder.RenameColumn(
                name: "ErrorMessage",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "error_message");

            migrationBuilder.RenameColumn(
                name: "EndedAt",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "ended_at");

            migrationBuilder.RenameColumn(
                name: "ArenaId",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "arena_id");

            migrationBuilder.RenameColumn(
                name: "Result_WinnerUnitId",
                schema: "game_runtime",
                table: "game_sessions",
                newName: "result_winner_unit_id");

            migrationBuilder.RenameColumn(
                name: "Id",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserLastName",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "user_last_name");

            migrationBuilder.RenameColumn(
                name: "UserId",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "user_id");

            migrationBuilder.RenameColumn(
                name: "UserFirstName",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "user_first_name");

            migrationBuilder.RenameColumn(
                name: "UnitType",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "unit_type");

            migrationBuilder.RenameColumn(
                name: "UnitName",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "unit_name");

            migrationBuilder.RenameColumn(
                name: "UnitId",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "unit_id");

            migrationBuilder.RenameColumn(
                name: "SessionId",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "session_id");

            migrationBuilder.RenameColumn(
                name: "JoinedAt",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "joined_at");

            migrationBuilder.RenameColumn(
                name: "CharacterSpecName",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "character_spec_name");

            migrationBuilder.RenameColumn(
                name: "CharacterClassName",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "character_class_name");

            migrationBuilder.RenameIndex(
                name: "IX_GameSessionParticipants_SessionId",
                schema: "game_runtime",
                table: "game_session_participants",
                newName: "ix_game_session_participants_session_id");

            migrationBuilder.RenameColumn(
                name: "Value",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "value");

            migrationBuilder.RenameColumn(
                name: "To_Y",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "to_y");

            migrationBuilder.RenameColumn(
                name: "To_X",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "to_x");

            migrationBuilder.RenameColumn(
                name: "Position_Y",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "position_y");

            migrationBuilder.RenameColumn(
                name: "Position_X",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "position_x");

            migrationBuilder.RenameColumn(
                name: "Info",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "info");

            migrationBuilder.RenameColumn(
                name: "Id",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "WalkLogEntry_FacingDirection",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "walk_log_entry_facing_direction");

            migrationBuilder.RenameColumn(
                name: "TurnIndex",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "turn_index");

            migrationBuilder.RenameColumn(
                name: "TargetName",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "target_name");

            migrationBuilder.RenameColumn(
                name: "TargetId",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "target_id");

            migrationBuilder.RenameColumn(
                name: "SessionId",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "session_id");

            migrationBuilder.RenameColumn(
                name: "PlacedItemId",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "placed_item_id");

            migrationBuilder.RenameColumn(
                name: "ItemType",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "item_type");

            migrationBuilder.RenameColumn(
                name: "ItemPickedUpLogEntry_Value",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "item_picked_up_log_entry_value");

            migrationBuilder.RenameColumn(
                name: "ItemName",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "item_name");

            migrationBuilder.RenameColumn(
                name: "ItemId",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "item_id");

            migrationBuilder.RenameColumn(
                name: "FacingDirection",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "facing_direction");

            migrationBuilder.RenameColumn(
                name: "EntryType",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "entry_type");

            migrationBuilder.RenameColumn(
                name: "EffectType",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "effect_type");

            migrationBuilder.RenameColumn(
                name: "CreatedAt",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "created_at");

            migrationBuilder.RenameColumn(
                name: "ActorName",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "actor_name");

            migrationBuilder.RenameColumn(
                name: "ActorId",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "actor_id");

            migrationBuilder.RenameColumn(
                name: "AbilityType",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "ability_type");

            migrationBuilder.RenameColumn(
                name: "AbilityName",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "ability_name");

            migrationBuilder.RenameColumn(
                name: "TargetHp_Max",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "target_hp_max");

            migrationBuilder.RenameColumn(
                name: "TargetHp_Current",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "target_hp_current");

            migrationBuilder.RenameColumn(
                name: "StatSnapshot_TargetHp_Max",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "actor_hp_max");

            migrationBuilder.RenameColumn(
                name: "StatSnapshot_TargetHp_Current",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "actor_hp_current");

            migrationBuilder.RenameIndex(
                name: "IX_GameActionLogEntries_SessionId",
                schema: "game_runtime",
                table: "game_action_log_entries",
                newName: "ix_game_action_log_entries_session_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_outbox_messages",
                schema: "integration",
                table: "outbox_messages",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_game_sessions",
                schema: "game_runtime",
                table: "game_sessions",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_game_session_participants",
                schema: "game_runtime",
                table: "game_session_participants",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_game_action_log_entries",
                schema: "game_runtime",
                table: "game_action_log_entries",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_game_action_log_entries_game_sessions_session_id",
                schema: "game_runtime",
                table: "game_action_log_entries",
                column: "session_id",
                principalSchema: "game_runtime",
                principalTable: "game_sessions",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_game_session_participants_game_sessions_session_id",
                schema: "game_runtime",
                table: "game_session_participants",
                column: "session_id",
                principalSchema: "game_runtime",
                principalTable: "game_sessions",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
