// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database.GameRuntime;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.GameRuntime.Migrations
{
    [DbContext(typeof(GameRuntimeDbContext))]
    [Migration("20260222210510_AddGameActionLogEntry")]
    partial class AddGameActionLogEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game_runtime")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.GameActionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Info")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("info");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("integer")
                        .HasColumnName("turn_index");

                    b.HasKey("Id")
                        .HasName("pk_game_action_log_entries");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_game_action_log_entries_session_id");

                    b.ToTable("game_action_log_entries", "game_runtime");

                    b.HasDiscriminator<int>("ActionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessionParticipants.GameSessionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_game_session_participants");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_game_session_participants_session_id");

                    b.ToTable("game_session_participants", "game_runtime");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessions.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uuid")
                        .HasColumnName("arena_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("error_message");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalTurns")
                        .HasColumnType("integer")
                        .HasColumnName("total_turns");

                    b.PrimitiveCollection<List<Guid>>("UserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("user_ids");

                    b.HasKey("Id")
                        .HasName("pk_game_sessions");

                    b.ToTable("game_sessions", "game_runtime");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.AttackLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.GameActionLogEntry");

                    b.Property<decimal>("Damage")
                        .HasColumnType("numeric")
                        .HasColumnName("damage");

                    b.Property<int>("FacingDirection")
                        .HasColumnType("integer")
                        .HasColumnName("facing_direction");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.ToTable("game_action_log_entries", "game_runtime");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.DeathLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.GameActionLogEntry");

                    b.ToTable("game_action_log_entries", "game_runtime");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.IdleLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.GameActionLogEntry");

                    b.ToTable("game_action_log_entries", "game_runtime");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.WalkLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.GameActionLogEntry");

                    b.Property<int>("FacingDirection")
                        .HasColumnType("integer")
                        .HasColumnName("facing_direction");

                    b.ToTable("game_action_log_entries", "game_runtime", t =>
                        {
                            t.Property("FacingDirection")
                                .HasColumnName("walk_log_entry_facing_direction");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.GameActionLogEntry", b =>
                {
                    b.HasOne("Domain.GameRuntime.GameSessions.GameSession", null)
                        .WithMany("ActionLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_action_log_entries_game_sessions_session_id");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessionParticipants.GameSessionParticipant", b =>
                {
                    b.HasOne("Domain.GameRuntime.GameSessions.GameSession", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_session_participants_game_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessions.GameSession", b =>
                {
                    b.OwnsOne("Domain.GameRuntime.GameResults.GameResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("GameSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Outcome")
                                .HasColumnType("integer")
                                .HasColumnName("result_outcome");

                            b1.Property<Guid?>("WinnerUnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("result_winner_unit_id");

                            b1.HasKey("GameSessionId");

                            b1.ToTable("game_sessions", "game_runtime");

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId")
                                .HasConstraintName("fk_game_sessions_game_sessions_id");
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.AttackLogEntry", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.StatSnapshot", "TargetHp", b1 =>
                        {
                            b1.Property<Guid>("AttackLogEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Current")
                                .HasColumnType("numeric")
                                .HasColumnName("target_hp_current");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric")
                                .HasColumnName("target_hp_max");

                            b1.HasKey("AttackLogEntryId");

                            b1.ToTable("game_action_log_entries", "game_runtime");

                            b1.WithOwner()
                                .HasForeignKey("AttackLogEntryId")
                                .HasConstraintName("fk_game_action_log_entries_game_action_log_entries_id");
                        });

                    b.Navigation("TargetHp")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.WalkLogEntry", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Position", "To", b1 =>
                        {
                            b1.Property<Guid>("WalkLogEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("to_x");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("to_y");

                            b1.HasKey("WalkLogEntryId");

                            b1.ToTable("game_action_log_entries", "game_runtime");

                            b1.WithOwner()
                                .HasForeignKey("WalkLogEntryId")
                                .HasConstraintName("fk_game_action_log_entries_game_action_log_entries_id");
                        });

                    b.Navigation("To")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessions.GameSession", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
