// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database.GameRuntime;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.GameRuntime.Migrations
{
    [DbContext(typeof(GameRuntimeDbContext))]
    [Migration("20260816232032_SlavicReworkLogs")]
    partial class SlavicReworkLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game_runtime")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.GameActionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("GameActionLogEntries", "game_runtime");

                    b.HasDiscriminator<int>("EntryType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessionParticipants.GameSessionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterClassName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CharacterSpecName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.Property<string>("UserFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("GameSessionParticipants", "game_runtime");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessions.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTurns")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<Guid>>("UserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.ToTable("GameSessions", "game_runtime");
                });

            modelBuilder.Entity("Domain.Integration.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "Type")
                        .IsUnique();

                    b.HasIndex("Type", "CreatedAtUtc", "Id");

                    b.ToTable("outbox_messages", "integration");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.AbilityUsedLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.Entries.GameActionLogEntry");

                    b.Property<string>("AbilityName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("AbilityType")
                        .HasColumnType("integer");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer");

                    b.Property<int>("FacingDirection")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.DeathLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.Entries.GameActionLogEntry");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.IdleLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.Entries.GameActionLogEntry");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.ItemPickedUpLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.Entries.GameActionLogEntry");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlacedItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.ToTable("GameActionLogEntries", "game_runtime", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("ItemPickedUpLogEntry_Value");
                        });

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.RoundStartedLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.Entries.GameActionLogEntry");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.StatusAppliedLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.Entries.GameActionLogEntry");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<decimal>("Magnitude")
                        .HasColumnType("numeric");

                    b.Property<int>("StatusType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.ToTable("GameActionLogEntries", "game_runtime", t =>
                        {
                            t.Property("TargetId")
                                .HasColumnName("StatusAppliedLogEntry_TargetId");

                            t.Property("TargetName")
                                .HasColumnName("StatusAppliedLogEntry_TargetName");
                        });

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.WalkLogEntry", b =>
                {
                    b.HasBaseType("Domain.GameRuntime.GameActionLogs.Entries.GameActionLogEntry");

                    b.Property<int>("FacingDirection")
                        .HasColumnType("integer");

                    b.ToTable("GameActionLogEntries", "game_runtime", t =>
                        {
                            t.Property("FacingDirection")
                                .HasColumnName("WalkLogEntry_FacingDirection");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.GameActionLogEntry", b =>
                {
                    b.HasOne("Domain.GameRuntime.GameSessions.GameSession", null)
                        .WithMany("ActionLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessionParticipants.GameSessionParticipant", b =>
                {
                    b.HasOne("Domain.GameRuntime.GameSessions.GameSession", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessions.GameSession", b =>
                {
                    b.OwnsOne("Domain.GameRuntime.GameResults.GameResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("GameSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Outcome")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("WinnerUnitId")
                                .HasColumnType("uuid");

                            b1.HasKey("GameSessionId");

                            b1.ToTable("GameSessions", "game_runtime");

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId");
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.AbilityUsedLogEntry", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.StatSnapshot", "TargetHp", b1 =>
                        {
                            b1.Property<Guid>("AbilityUsedLogEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Current")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric");

                            b1.HasKey("AbilityUsedLogEntryId");

                            b1.ToTable("GameActionLogEntries", "game_runtime");

                            b1.WithOwner()
                                .HasForeignKey("AbilityUsedLogEntryId");
                        });

                    b.Navigation("TargetHp")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.ItemPickedUpLogEntry", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.StatSnapshot", "ActorHp", b1 =>
                        {
                            b1.Property<Guid>("ItemPickedUpLogEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Current")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric");

                            b1.HasKey("ItemPickedUpLogEntryId");

                            b1.ToTable("GameActionLogEntries", "game_runtime");

                            b1.WithOwner()
                                .HasForeignKey("ItemPickedUpLogEntryId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("ItemPickedUpLogEntryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("ItemPickedUpLogEntryId");

                            b1.ToTable("GameActionLogEntries", "game_runtime");

                            b1.WithOwner()
                                .HasForeignKey("ItemPickedUpLogEntryId");
                        });

                    b.Navigation("ActorHp")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.StatusAppliedLogEntry", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.StatSnapshot", "TargetHp", b1 =>
                        {
                            b1.Property<Guid>("StatusAppliedLogEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Current")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Max")
                                .HasColumnType("numeric");

                            b1.HasKey("StatusAppliedLogEntryId");

                            b1.ToTable("GameActionLogEntries", "game_runtime", t =>
                                {
                                    t.Property("Current")
                                        .HasColumnName("StatSnapshot_TargetHp_Current");

                                    t.Property("Max")
                                        .HasColumnName("StatSnapshot_TargetHp_Max");
                                });

                            b1.WithOwner()
                                .HasForeignKey("StatusAppliedLogEntryId");
                        });

                    b.Navigation("TargetHp");
                });

            modelBuilder.Entity("Domain.GameRuntime.GameActionLogs.Entries.WalkLogEntry", b =>
                {
                    b.OwnsMany("Domain.ValueObjects.Position", "Path", b1 =>
                        {
                            b1.Property<Guid>("WalkLogEntryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("X");

                            b1.Property<int>("Y");

                            b1.HasKey("WalkLogEntryId", "__synthesizedOrdinal");

                            b1.ToTable("GameActionLogEntries", "game_runtime");

                            b1
                                .ToJson("Path")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WalkLogEntryId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Position", "To", b1 =>
                        {
                            b1.Property<Guid>("WalkLogEntryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("WalkLogEntryId");

                            b1.ToTable("GameActionLogEntries", "game_runtime");

                            b1.WithOwner()
                                .HasForeignKey("WalkLogEntryId");
                        });

                    b.Navigation("Path");

                    b.Navigation("To")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.GameRuntime.GameSessions.GameSession", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
